### ISSUE TITLE
Setting dropdown width within a px-card

### ISSUE THREAD

**Issue by vr237** [predixdesignsystem/px-dropdown#103] opened 2019-02-21 13:34 UTC
Pre the 4.9.2 release, we were using the `--px-dropdown-min-width` property to make the dropdown take the full (100%) width of the px-card that it's contained in (this included the dropdown items and the trigger itself). After the latest release, this property was removed from the dropdown trigger - is there an alternative way now to provide a minimum width for the trigger so that it takes up the whole width of the px-card?

**Comment by evanjd** [comment] 2019-03-03 23:03
Sorry for the slow reply @vr237. We removed it from the trigger because it was causing issues for menus with icon triggers.

You should be able to set the `width` or `min-width` CSS prop directly on the element to resize the trigger, or set `--px-dropdown-flex-grow: 1` to have the dropdown fill the available space. Let me know if this doesn't work.

**Comment by vr237** [comment] 2019-03-04 10:06
Hi Evan,

Thanks for the reply. Setting the width of the px-dropdown to 100% works, but we need to set `--px-dropdown-max-width` to 100% in `:host` as well (at least in our case). We will go with this solution.

**Comment by evanjd** [comment] 2019-03-05 02:09
Thanks @vr237 and sorry for the surprise regression. I'll close this given your comment, feel free to comment and I'll reopen should you run into any further issues.

**Closed by evanjd** 2019-03-05 02:09 UTC
