### ISSUE TITLE
Unable to control number of suggestions before introduce scrolling and the no option to clear the values on the typeahead of the dropdown

### ISSUE THREAD

**Issue by AnurudhaNagarajan** [predixdesignsystem/px-dropdown#87] opened 2018-08-27 09:56 UTC
https://px-dropdown-issue.glitch.me/

**Comment by AnurudhaNagarajan** [comment] 2018-08-27 09:57
Also when I add a long name, I am unable to control the width of the trigger. If I control the width, then it overlaps the other element

**Comment by evanjd** [comment] 2018-08-27 10:40
Both the maximum height and width can be controlled by setting the `--px-dropdown-max-height` and `--px-dropdown-max-width` CSS properties.

I've remixed your glitch to demonstrate: https://px-dropdown-set-max-size.glitch.me/ ([edit link](https://glitch.com/edit/#!/px-dropdown-set-max-size)). In this example, I've set the maximum height to 600px and the maximum width to 250px.

**Comment by AnurudhaNagarajan** [comment] 2018-08-27 10:55
yes I think it should be called the search

**Comment by AnurudhaNagarajan** [comment] 2018-08-27 10:56
One more thing the major issue now is the overlap of the element.

**Comment by AnurudhaNagarajan** [comment] 2018-08-27 11:00
![overlap](https://user-images.githubusercontent.com/18552273/44656442-77295500-aa16-11e8-9f85-d7cd9604fd90.PNG)

**Comment by AnurudhaNagarajan** [comment] 2018-08-27 11:01
I am unable to control the trigger

**Comment by evanjd** [comment] 2018-08-27 11:03
It's still not at all clear what problem you're trying to describe when you say:

> the no option to clear the values on the typeahead of the dropdown

If you mean the search, just click the field and remove the text. If you mean something else, please provide clear, descriptive steps to reproduce.

**Comment by evanjd** [comment] 2018-08-27 11:06
The dropdown value not truncating on long items has already been raised: https://github.com/predixdesignsystem/px-dropdown/issues/86

**Comment by evanjd** [comment] 2018-08-27 11:36
OK, that's a feature request. I'm not sure it really makes sense for dropdown, why not use [px-typeahead](https://www.predix-ui.com/#/elements/px-typeahead)?

I'm closing this as it's already gotten really messy. But in summary:

- Issue 1: **Cannot set max width and height**. Not a bug - have provided CSS variables and example.
- Issue 2: **Long items are not truncated**. Duplicate - see https://github.com/predixdesignsystem/px-dropdown/issues/86
- Issue 3: **Feature request for X button to dismiss dropdown filter**. Have you considered using [px-typeahead](https://www.predix-ui.com/#/elements/px-typeahead)?

Also, in future, please fill out the issue form. The glitch was a big help but clear reproduction steps and the precise behaviour you expect will remove this need for this time consuming back and forth. Also, if you have multiple issues, raise them separately. Thanks.

**Closed by evanjd** 2018-08-27 11:36 UTC
